# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get uuid-test could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/uuid-test/0.1.0"
SRC_URI += "git://git@github.com/akiernan/uuid-test.git;protocol=ssh;nobranch=1"
SRCREV = "370eff540171d64d1a724543977791724dd5bbf9"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+370eff5401"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/getrandom/0.2.8 \
    crate://crates.io/libc/0.2.137 \
    crate://crates.io/wasi/0.11.0+wasi-snapshot-preview1 \
    git://github.com/uuid-rs/uuid.git;protocol=https;nobranch=1;name=uuid;destsuffix=uuid \
"

SRCREV_FORMAT .= "_uuid"
SRCREV_uuid = "f5a29cf3d11f8a6a431e0aae3e3a6f9530498a4e"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "uuid-test"
HOMEPAGE = "https://github.com/akiernan/uuid-test.git"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include uuid-test-${PV}.inc
include uuid-test.inc
